export const colors = {
	COLOR_PRIMARY: "#87bfd7",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};

//  Data for categories filter

export const categories = [
	{
		id: "01",
		category: "Restaurants",
	},
	{
		id: "02",
		category: "Fashion",
	},
	{
		id: "03",
		category: "Grocery",
	},
	{
		id: "04",
		category: "Health Services",
	},
	{
		id: "05",
		category: "Banking",
	},
	{
		id: "06",
		category: "Church",
	},
	{
		id: "07",
		category: "Other"
	}
	
];

export const recipeList = [
	{
		id: "01",
		categoryId: "01",
		name: "16 Prospect Wine Bar",
		image: require("../assets/images/16Prospect.png"),
		rating: "4.7",
		ingredients: ["Ramp leads up to entrance, good wide entrance"],
		time: "5/5",
		difficulty: "4/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"Quirky decor & regular live jazz sessions lend this casual American-Italian bistro a bohemian vibe.",
		penises: ["Slightly crammed, higher wooden seats"],
		dicks: ["2 spots in the lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest",
	},
	{
		id: "02",
		categoryId: "01",
		name: "1958 Cuban Cuisine",
		image: require("../assets/images/1958CubanCuisine.png"),
		rating: "4.0",
		ingredients: ["Large step in the front"],
		time: "3/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "03",
		categoryId: "01",
		name: "Addams Tavern",
		image: require("../assets/images/addams.png"),
		rating: "5.0",
		ingredients: ["All good/only first floor as second floor requires stairs"],
		time: "5/5",
		difficulty: "5/5",
		calories: "5/5",
		color: "#006A4E",
		description:
			"New American plates pair with wine in a fashionable setting for lunch, dinner & weekend brunch.",
		penises: ["Spacious and wheelchair accommodating"],
		dicks: ["Trader joe's lot down the street, 12 spots "],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "04",
		categoryId: "01",
		name: "Ahrre's Coffee",
		image: require("../assets/images/Ahrre.png"),
		rating: "3.7",
		ingredients: ["Not large enough, many steps leading up"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Coffee roastery.",
		penises: ["Crammed Interior"],
		dicks: ["Baron's parking lot in the rear"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest outside"
	},
	{
		id: "05",
		categoryId: "01",
		name: "Akai Japanese Sushi",
		image: require("../assets/images/Akai.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Modern Japanese restaurant serving a wide variety of traditional and innovative Japanese cuisine with a full bar offering martinis, wines and sakes.",
		penises: ["Good Interior, happy to accommodate in seating"],
		dicks: ["Lot #7 a block down"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "06",
		categoryId: "01",
		name: "Bovellas Pastry Shoppe",
		rating: "4.7",
		image: require("../assets/images/Bovellas.png"),
		ingredients: ["Adequate pull-side clearance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Long-standing, mom-&-pop bakeshop offering a range of gourmet, kosher pastries, treats & desserts.",
		penises: ["Slightly crammed interior, seating might be hard for wheelchair"],
		dicks: ["Trader joe's lot 12 spots down the street"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"

	},
	{
		id: "07",
		categoryId: "01",
		name: "Boxwood Coffee Roasters",
		image: require("../assets/images/Boxwood.png"),
		rating: "4.7",
		ingredients: ["Wide and accessible entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"A family run coffee roastery providing high quality coffee & tea.",
		penises: ["Wide interior with both high top and accessible seating"],
		dicks: ["Trader joe's lot 12 spots in the rear"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "08",
		categoryId: "01",
		name: "Brick Oven",
		image: require("../assets/images/brickoven.png"),
		rating: "4.7",
		ingredients: ["Good entrance, no steps"],
		time: "5/5",
		difficulty: "5/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Cozy BYOB restaurant serving up traditional Italian pastas & meats roasted in a wood-burning oven.",
		penises: ["Wide aisles, easy wheelchair maneuverability"],
		dicks: ["Quimby st parking no spots, Lot #7 5 spots down Central Ave"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "09",
		categoryId: "01",
		name: "Brunella Coffee & Deli",
		image: require("../assets/images/brunella.png"),
		rating: "3.3",
		ingredients: ["Has a step in front of the door"],
		time: "3/5",
		difficulty: "4/5",
		calories: "3/5",
		color: "#006A4E",
		description:
			"Portuguese Coffee & Deli",
		penises: ["Slightly crammed Interior"],
		dicks: ["Quimby st parking no spots, Lot #7 5 spots down Central Ave"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},

	{
		id: "11",
		categoryId: "01",
		name: "Casa di Pizza",
		image: require("../assets/images/casa.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Slightly crammed Interior"],
		dicks: ["Train lot across the street"],
		bathroom: "✔️ Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "12",
		categoryId: "01",
		name: "Chez Catherine",
		image: require("../assets/images/chezcatherine.png"),
		rating: "4.7",
		ingredients: ["Good entrance"],
		time: "5/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Elegant French restaurant offering upmarket à la carte lunches & fixed-price dinners.",
		penises: ["Good Interior, happy to accommodate in seating"],
		dicks: ["Lot #2 a block down"],
		bathroom: "✗ No Wheelchair Accessible Restroom",
		seating: "✔️ Place to sit down to rest"
	},
	{
		id: "13",
		categoryId: "01",
		name: "Chipotle",
		image: require("../assets/images/chipotle.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "14",
		categoryId: "01",
		name: "Chocolate Bar",
		image: require("../assets/images/Chocolate-bar-westfield.png"),
		rating: "4.7",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "15",
		categoryId: "01",
		name: "Chutzpah Kitchen",
		image: require("../assets/images/images.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "16",
		categoryId: "01",
		name: "Cinnaholic",
		image: require("../assets/images/Cinnaholic.png"),
		rating: "3.9",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "17",
		categoryId: "01",
		name: "Cold Stone Creamery",
		image: require("../assets/images/coldstone.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "18",
		categoryId: "01",
		name: "Cosimo",
		image: require("../assets/images/cosimo.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "19",
		categoryId: "01",
		name: "Di Farina Pizzeria",
		image: require("../assets/images/difarina.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "20",
		categoryId: "01",
		name: "Farinolio",
		image: require("../assets/images/farinolio.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	
	{
		id: "22",
		categoryId: "01",
		name: "Ferraro's Restaurant",
		image: require("../assets/images/ferraro.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "23",
		categoryId: "01",
		name: "Flamma Pizza",
		image: require("../assets/images/flamma.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "24",
		categoryId: "01",
		name: "Five Guys",
		image: require("../assets/images/fiveguys.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "25",
		categoryId: "01",
		name: "Fresh Bui",
		image: require("../assets/images/fresh.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "26",
		categoryId: "01",
		name: "FroYo",
		image: require("../assets/images/Froyo.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "27",
		categoryId: "01",
		name: "Hershey's Deli",
		image: require("../assets/images/hershey.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "28",
		categoryId: "01",
		name: "Hunan Wok III",
		image: require("../assets/images/hunan.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "29",
		categoryId: "01",
		name: "Inspiration Roll",
		image: require("../assets/images/inspiration.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "30",
		categoryId: "01",
		name: "Jade Garden",
		image: require("../assets/images/jade.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "31",
		categoryId: "01",
		name: "James Ward Mansion",
		image: require("../assets/images/jamesward.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "32",
		categoryId: "01",
		name: "JD' Caterers",
		image: require("../assets/images/jd.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "33",
		categoryId: "01",
		name: "Juice Junky",
		image: require("../assets/images/juice.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "34",
		categoryId: "01",
		name: "Kilwins",
		image: require("../assets/images/kilwins.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "35",
		categoryId: "01",
		name: "Limani Seafood Grill",
		image: require("../assets/images/limani.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "36",
		categoryId: "01",
		name: "Lions Roar",
		image: require("../assets/images/lions.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "37",
		categoryId: "01",
		name: "Manhatten Bagel",
		image: require("../assets/images/manhattan.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "38",
		categoryId: "01",
		name: "Maya Thai Eatery",
		image: require("../assets/images/maya.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "39",
		categoryId: "01",
		name: "Mulberry House",
		image: require("../assets/images/mulberry.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "40",
		categoryId: "01",
		name: "Nagoya",
		image: require("../assets/images/nagoya.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "41",
		categoryId: "01",
		name: "Nathan Hotdog",
		image: require("../assets/images/nathan.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "42",
		categoryId: "01",
		name: "NY Korean Barbeque",
		image: require("../assets/images/korean.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "43",
		categoryId: "01",
		name: "Old Havana",
		image: require("../assets/images/havana.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "44",
		categoryId: "01",
		name: "Ono Bowls",
		image: require("../assets/images/ono.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "45",
		categoryId: "01",
		name: "Orgreen Poke",
		image: require("../assets/images/orgreen.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "46",
		categoryId: "01",
		name: "Outta hand Pizza",
		image: require("../assets/images/outta.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "47",
		categoryId: "01",
		name: "Qdoba Mexican Eats",
		image: require("../assets/images/Qdoba.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "48",
		categoryId: "01",
		name: "Rockn' Joe",
		image: require("../assets/images/rockn.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	
	{
		id: "49",
		categoryId: "01",
		name: "Vicki's Diner",
		image: require("../assets/images/vicki.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "50",
		categoryId: "01",
		name: "Westfield Diner",
		image: require("../assets/images/westfield.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "51",
		categoryId: "01",
		name: "Westfield Seafood",
		image: require("../assets/images/seafood.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},


	{
		id: "52",
		categoryId: "02",
		name: "Adlers Jewelers",
		image: require("../assets/images/Adlers.png"),
		rating: "3.9",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Time-tested, family-owned store offering jewelry & watches as well as appraisals & repairs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "53",
		categoryId: "02",
		name: "American Shoe Repair",
		image: require("../assets/images/american.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "54",
		categoryId: "02",
		name: "Athleta",
		image: require("../assets/images/Athleta.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "55",
		categoryId: "02",
		name: "Banana Republic",
		image: require("../assets/images/Banana.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "56",
		categoryId: "02",
		name: "Bespoke by Gambert",
		image: require("../assets/images/Bespoke.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "57",
		categoryId: "02",
		name: "Best Foot Forward",
		image: require("../assets/images/best.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "58",
		categoryId: "02",
		name: "Beyond Trends",
		image: require("../assets/images/Beyond.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "59",
		categoryId: "02",
		name: "Bridget's Irish Cottages",
		image: require("../assets/images/Bridget.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "60",
		categoryId: "02",
		name: "Claire's",
		image: require("../assets/images/Claire.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "60",
		categoryId: "02",
		name: "Continental Tailoring",
		image: require("../assets/images/Continental.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "61",
		categoryId: "03",
		name: "Elegant Image",
		image: require("../assets/images/Elegant.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "62",
		categoryId: "02",
		name: "Evalyn Dunn",
		image: require("../assets/images/Evalyn.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "63",
		categoryId: "02",
		name: "Facial Reality Spa",
		image: require("../assets/images/Facial.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "64",
		categoryId: "02",
		name: "Flair Cleaners",
		image: require("../assets/images/Flair.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "65",
		categoryId: "02",
		name: "G O Keller's Inc",
		image: require("../assets/images/GO.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "66",
		categoryId: "02",
		name: "Gap",
		image: require("../assets/images/Gap.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "67",
		categoryId: "02",
		name: "Glamourous Girlz",
		image: require("../assets/images/Glamourous.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "68",
		categoryId: "02",
		name: "Gordin & Sons",
		image: require("../assets/images/Gordin.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "69",
		categoryId: "02",
		name: "Guillotine Salon",
		image: require("../assets/images/Guillotine.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "70",
		categoryId: "02",
		name: "Haircut Bar",
		image: require("../assets/images/Haircut.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "71",
		categoryId: "02",
		name: "Hope Chest",
		image: require("../assets/images/Hope.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "72",
		categoryId: "02",
		name: "Indigo Art Studio",
		image: require("../assets/images/Indigo.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "73",
		categoryId: "02",
		name: "J. McLaughlin",
		image: require("../assets/images/J.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "74",
		categoryId: "02",
		name: "JackRabbit x Fleet Feet",
		image: require("../assets/images/JackRabbit.png"),
		rating: "4.2",
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "75",
		categoryId: "02",
		name: "John Robert Custom",
		image: require("../assets/images/John.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "76",
		categoryId: "02",
		name: "Jos A Bank",
		image: require("../assets/images/Jos.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "77",
		categoryId: "02",
		name: "Jude Connally",
		image: require("../assets/images/Jude.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "78",
		categoryId: "02",
		name: "Kennedy's Barber",
		image: require("../assets/images/Kennedy.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "79",
		categoryId: "02",
		name: "Luigino Tailor",
		image: require("../assets/images/Luigino.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "80",
		categoryId: "02",
		name: "Luna Grace Beauty",
		image: require("../assets/images/Luna.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "81",
		categoryId: "02",
		name: "Madeline Moss",
		image: require("../assets/images/Madeline.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "82",
		categoryId: "02",
		name: "Michaelangelo",
		image: require("../assets/images/Michealangelo.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "83",
		categoryId: "02",
		name: "Mimi & Hill",
		image: require("../assets/images/Mimi.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "84",
		categoryId: "02",
		name: "N&C Jewelers",
		image: require("../assets/images/N.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "85",
		categoryId: "02",
		name: "Nails Spa & Beyond",
		image: require("../assets/images/nails.png"),
		rating: "4.2",
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "86",
		categoryId: "02",
		name: "Patricia & Paul",
		image: require("../assets/images/Patricia.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "87",
		categoryId: "02",
		name: "R Studio",
		image: require("../assets/images/R.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "88",
		categoryId: "02",
		name: "Salon Peak",
		image: require("../assets/images/SalonVisage.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "89",
		categoryId: "02",
		name: "Sherwin-Williams",
		image: require("../assets/images/Sherwin.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "90",
		categoryId: "02",
		name: "Starlight Cleaners",
		image: require("../assets/images/Starlight.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "91",
		categoryId: "02",
		name: "Supercuts",
		image: require("../assets/images/Supercuts.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "92",
		categoryId: "02",
		name: "Tamar Jewelery",
		image: require("../assets/images/Tamar.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "93",
		categoryId: "02",
		name: "The Device Shop",
		image: require("../assets/images/TheDevice.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "94",
		categoryId: "02",
		name: "U Relax Spa",
		image: require("../assets/images/URelax.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "95",
		categoryId: "02",
		name: "Urban Outfitters",
		image: require("../assets/images/Urban.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "96",
		categoryId: "02",
		name: "Warby Parker",
		image: require("../assets/images/Warby.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "97",
		categoryId: "02",
		name: "Westfield Tailors",
		image: require("../assets/images/WestfieldTailors.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "98",
		categoryId: "02",
		name: "Winnie Nails Spa",
		image: require("../assets/images/Winnie.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "99",
		categoryId: "02",
		name: "Wolves Den",
		image: require("../assets/images/WolvesDen.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "100",
		categoryId: "03",
		name: "Baron's Drug Store",
		image: require("../assets/images/barons.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	
	{
		id: "102",
		categoryId: "03",
		name: "Trader Joe's",
		image: require("../assets/images/Trader.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "103",
		categoryId: "03",
		name: "Walgreens",
		image: require("../assets/images/Walgreens.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "104",
		categoryId: "03",
		name: "Westfield Pharmacy",
		image: require("../assets/images/Pharmacy.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "105",
		categoryId: "03",
		name: "Westfield Seafood",
		image: require("../assets/images/seafood.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "106",
		categoryId: "04",
		name: "Atlantic Medical",
		image: require("../assets/images/atlantic.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "107",
		categoryId: "04",
		name: "Baron's Drug",
		image: require("../assets/images/Baron.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "108",
		categoryId: "04",
		name: "Brunner Eye Care",
		image: require("../assets/images/brunner.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "109",
		categoryId: "04",
		name: "Club Pilates",
		image: require("../assets/images/PilatesC.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "110",
		categoryId: "04",
		name: "Dentologem",
		image: require("../assets/images/Dentologem.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "111",
		categoryId: "04",
		name: "Green Room",
		image: require("../assets/images/Green.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "112",
		categoryId: "04",
		name: "Haven Pelvic PT",
		image: require("../assets/images/Haven.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "113",
		categoryId: "04",
		name: "HearingLife",
		image: require("../assets/images/HearingL.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "114",
		categoryId: "04",
		name: "I to Eye",
		image: require("../assets/images/I.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "115",
		categoryId: "04",
		name: "JAG-ONE",
		image: require("../assets/images/JAG.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "116",
		categoryId: "04",
		name: "Laser Dental",
		image: require("../assets/images/Laser.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "117",
		categoryId: "04",
		name: "Lavy House Senior",
		image: require("../assets/images/Lavy.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "118",
		categoryId: "04",
		name: "Professional PT",
		image: require("../assets/images/ProfessionalPT.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "119",
		categoryId: "04",
		name: "Raritan Valley Gyrotonic",
		image: require("../assets/images/Raritan.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "120",
		categoryId: "04",
		name: "Satsang Yoga Studio",
		image: require("../assets/images/Satsang.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "121",
		categoryId: "05",
		name: "Bank of America",
		image: require("../assets/images/BOA.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "122",
		categoryId: "05",
		name: "Chase Bank",
		image: require("../assets/images/Chase.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "123",
		categoryId: "05",
		name: "Haven Savings Bank",
		image: require("../assets/images/Haven.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "124",
		categoryId: "05",
		name: "PNC Bank",
		image: require("../assets/images/PNC.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},

	{
		id: "125",
		categoryId: "05",
		name: "Wells Fargo",
		image: require("../assets/images/Wells.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},

	{
		id: "126",
		categoryId: "06",
		name: "First Baptist Church",
		image: require("../assets/images/Baptist.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},

	{
		id: "127",
		categoryId: "06",
		name: "First Congregational Church",
		image: require("../assets/images/Congregational.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},

	{
		id: "128",
		categoryId: "06",
		name: "First United Methodist",
		image: require("../assets/images/United.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "129",
		categoryId: "07",
		name: "AT&T",
		image: require("../assets/images/att.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "130",
		categoryId: "07",
		name: "Mimi & Hill Design",
		image: require("../assets/images/Mimi.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "131",
		categoryId: "07",
		name: "New Gymnasium",
		image: require("../assets/images/newgym.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "132",
		categoryId: "07",
		name: "NosVino",
		image: require("../assets/images/nos.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "133",
		categoryId: "07",
		name: "T-Mobile",
		image: require("../assets/images/T.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "134",
		categoryId: "07",
		name: "The Device Shop",
		image: require("../assets/images/TheDevice.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "135",
		categoryId: "07",
		name: "UPS Store",
		image: require("../assets/images/ups.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},
	{
		id: "136",
		categoryId: "07",
		name: "Verizon",
		image: require("../assets/images/verizon.png"),
		rating: "4.2",
		ingredients: ["Large step in the front"],
		time: "2/5",
		difficulty: "5/5",
		calories: "4/5",
		color: "#006A4E",
		description:
			"Warm, family-owned BYOB eatery with Cuban art offering modern & traditional dishes in homey digs.",
		penises: ["Spacious Interior"],
		dicks: ["Train lot across the street"],
	},











	 
	
	

	
	


];
